### ISSUE TITLE
v1.0.1

### ISSUE THREAD

**Issue by sanemat** [kevva/lnfs#2]
Would you release v1.0.1?
I want to use CLI.

**Comment by kevva** [comment]
Oh, thought I did already.

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/lnfs/commit/addb8febcc7cb4aebbc289866e54229f87aa8a5a.

**Comment by sanemat** [comment]
@kevva Thanks! :smile:

**Comment by kevva** [comment]
Install `lnfs-cli` instead if you want to stay updated :). I've split up the API and CLI.

**Comment by sanemat** [comment]
awesome!
